### ISSUE TITLE
Please add NSFW score property to ImageClassifier

### ISSUE THREAD

**Issue by whiskman** [TechnikEmpire/NsfwNET#10]
I like your job and the performance. But i'll be nice to have nsfw score property available. Thanks.

**Comment by TechnikEmpire** [comment]
I was thinking the same thing today. I have an update coming up today, should be able to roll that in.

**Comment by TechnikEmpire** [comment]
@whiskman This is done in 1.1.0 which should be visible on Nuget at any time.

**Comment by whiskman** [comment]
Thank you!  I'll try it.
