### ISSUE TITLE
Bad jpg terminate application in v1.1, but in 1.0.1 just print CV error

### ISSUE THREAD

**Issue by whiskman** [TechnikEmpire/NsfwNET#13]
Testing new release  (program.cs) I found a misformed jpg image terminate console appplication. In the previous versión just output CV error and continues to classify. 

The error:
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in cv::resize, file C:\dev\lib\opencv-3.3.1\modules\imgproc\src\resize.cpp, line 3289

Same way, file types other tan images (e.g. .zip) will do the same, and the previous version just print the error. 

Attached sample problematic image.

![0002323_carved](https://user-images.githubusercontent.com/35151638/34742976-06891704-f580-11e7-8927-32c6e7761440.jpeg)
[0002323_Carved.zip](https://github.com/TechnikEmpire/NsfwNET/files/1616701/0002323_Carved.zip)

**Comment by TechnikEmpire** [comment]
@whiskman Thanks for the report, I'll have a look.

**Comment by whiskman** [comment]
Hi. Any news on this issue?     
If you are busy right now it would be very useful if you can simply add the score property avilable to the previous versión 1.0.1 that works nicely, tested on large amount of images with very good results.
Thanks.

**Comment by TechnikEmpire** [comment]
Hey sorry for nor replying. I've been swamped with garbage. Anyway I'll fix this up tonight, I'll just build against opencv 3.4.1 since it's newly released and make sure it's failing safely 

In terms of the score property, I wasn't aware there was an issue (or maybe I just forgot). Can you clarify?

**Comment by whiskman** [comment]
The issue is just the original reported (terminate console app with some image files in v1.1) . The score property that you added to v1.1 happens to be very useful (I include it into a json report of all scanned images) for further filtering and processing. So I just wonder, maybe is just easier for you to add the property to previous version until you can find the time to fix the new one. But if you planned to commit an update, awesome then!.

We are testing Yahoo's model in a small forensic lab to help fighting against child abuse, etc. And your solution seems to be fast and simple to use. Todas I process about 280000 images in aprox 2:10 hs (Intel i7, 32GB ram, sdd disk), very good result.
Thank you.

**Comment by TechnikEmpire** [comment]
@whiskman That's very admirable work and thank you for this service you guys are providing. If you feel like it, please, let me know more information about you guys as I'd be very interested to know more. I'm so happy to hear that somehow I might be able to help with such an important thing. I'll push an update fixing this later tonight.

I was planning on running some refinement training on my squeezenet model to improve accuracy but I've been putting it off. If you guys are using that model, I'll make that a priority. Let me know.

**Comment by TechnikEmpire** [comment]
@whiskman Also I have an unpublished library that can classify video. If that would be of use to you guys let me know, I can make a neat and simple .NET package with that bundled in. It can handle streaming over a network and leverages DirectX and Windows directshow filters for decoding. I'll publish it open source if that sounds like something that you guys could use. Alternatively, there's C++ code already in this repo for that reading from files using ffmpeg for decoding. [Video of that code in action](https://www.youtube.com/watch?v=UAlVOGf9V1s).

**Comment by TechnikEmpire** [comment]
I haven't forgotten about this. I recompiled with opencv 3.4.1 but performance got cut in half. No idea what happened. So I have to either solve that or revert to previous version of opencv.

**Comment by TechnikEmpire** [comment]
@whiskman this is fixed in https://github.com/TechnikEmpire/NsfwNET/releases/tag/v1.2.0

Just uploaded to Nuget now, so it should up in your package manager within a couple of hours.

**Comment by whiskman** [comment]
Thank you Jesse!  I'll try it later.
Best regards.
