### ISSUE TITLE
Yahoo's nsfw model linked in submodule doesn't load

### ISSUE THREAD

**Issue by scottbouma** [TechnikEmpire/NsfwNET#14]
Hi.  Thanks so much for making this available!  It's been a great example for me to follow as I try to get Yahoo's nsfw model working in my own project. 

I can load and run your  model in Contrib/NsfwSqueezenet/ just fine, but when I try to load Yahoo's model under Contrib/OpenNSFW/, I get the parse errors below from OpenCV's dnn::readNetFromCaffe(...).

Any suggestions?  Thanks!

OpenCV Error: Unspecified error (FAILED: ReadProtoFromBinaryFile(param_file, param). Failed to parse NetParameter file: /home/sbouma/scratch/NsfwNET/NsfwNetNative/Contrib/OpenNSFW/nsfw_model/resnet_50_1by2_nsfw.caffemodel) in ReadNetParamsFromBinaryFileOrDie, file /home/sbouma/opencv-3.4.0/modules/dnn/src/caffe/caffe_io.cpp, line 1159
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/sbouma/opencv-3.4.0/modules/dnn/src/caffe/caffe_io.cpp:1159: error: (-2) FAILED: ReadProtoFromBinaryFile(param_file, param). Failed to parse NetParameter file: /home/sbouma/scratch/NsfwNET/NsfwNetNative/Contrib/OpenNSFW/nsfw_model/resnet_50_1by2_nsfw.caffemodel in function ReadNetParamsFromBinaryFileOrDie

**Comment by TechnikEmpire** [comment]
Oh dear I must have forgotten to update this. I built this with the opencv 3.4 release candidate and they had a bug where they broke the reading of layers in resnet. They patched it now but the solution is to either downgrade it to opencv 3.3.x or build from master. I thought for sure I updated this. Is this from nuget or what?

**Comment by TechnikEmpire** [comment]
Nevermind you must be using opencv 3.4 directly. Build from master or downgrade to 3.3 that'll fix it.

**Comment by TechnikEmpire** [comment]
lol if I had of taken a breath and finished reading your whole bug ticket I woulda seen the `3.4` in your stack trace. The solution I mentioned above is the correct one. See https://github.com/opencv/opencv/issues/10530 if you're interested.

**Comment by scottbouma** [comment]
Thanks for the quick reply!  I'll downgrade to 3.3 and try again.

**Comment by TechnikEmpire** [comment]
As far as this network goes, you're not missing much of anything by going down to 3.3.
