### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by zephyrprime** [TechnikEmpire/NsfwNET#22]
OpenCv 3.4.1 doesn't even have a a opencv_core341.lib which is referenced in this project.  It only has a opencv_core341_world341.lib.  Also, the correct library path is $(OPENCV_3_4_1)\$(PlatformTargetAsMSBuildArchitecture)\vc15\lib not $(OPENCV_3_3)\build\$(PlatformTargetAsMSBuildArchitecture)\install\lib.  And you didn't define $(OPENCV_3_3) anywhere either.  You should have included a project property file for that even if each user needs to change its value.

**Comment by TechnikEmpire** [comment]
You compiled opencv wrong.

Also this project is long-abandoned garbage.

**Comment by TechnikEmpire** [comment]
Just for future reference if you want experts to help you, its probably a bad idea to approach them with raw, unadulterated criticism and finger pointing.
